---

# Automatically build, validate, and deploy the devbox project

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

# Build the docker images
verify_build:
  stage: test
  image: maven:3.5.3-jdk-8
  script:
    # Running individually and via 'all' to test the script itself.
    # Won't have much overhead since redundant docker builds are fast.
    - ${CI_PROJECT_DIR}/scripts/build.sh vanilla
    - ${CI_PROJECT_DIR}/scripts/build.sh maven
    - ${CI_PROJECT_DIR}/scripts/build.sh devbox
    - ${CI_PROJECT_DIR}/scripts/build.sh all

deploy:
  stage: deploy
  image: maven:3.5.3-jdk-8
  only:
    - master
    - tags
  script:
    - echo "Updating the maven version to ${CI_COMMIT_TAG}"
    - echo "TODO" #TODO
    - echo "Building the docker images, tagging as '${CI_COMMIT_TAG}' and 'latest', and pushing to registry..."
    - ${CI_PROJECT_DIR}/scripts/build.sh -v "${CI_COMMIT_TAG}" -v "latest" -p all
